# Autogenerated wrapper script for COSTA_jll for x86_64-apple-darwin-mpi+mpitrampoline
export libcosta

using CompilerSupportLibraries_jll
using LLVMOpenMP_jll
using MPItrampoline_jll
JLLWrappers.@generate_wrapper_header("COSTA")
JLLWrappers.@declare_library_product(libcosta, "@rpath/libcosta.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, LLVMOpenMP_jll, MPItrampoline_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libcosta,
        "lib/libcosta.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
